logging:
  level:
    root: info

server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  config:
    import:
      - classpath:application-data.yml
      - classpath:application-lib.yml

app:
  cors:
    allowed-origins:
      - ${APP_CORS_ALLOWED_ORIGINS}
  mq:
    pub-enabled: ${MESSAGE_QUEUE_PUB_ENABLED}
    sub-enabled: ${MESSAGE_QUEUE_SUB_ENABLED}