logging:
  level:
    root: info

server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  config:
    import:
      - classpath:application-data.yml
      - classpath:application-lib.yml

app:
  cors:
    allowed-origins:
      - ${APP_CORS_ALLOWED_ORIGINS}
  debate:
    max-member-count: ${APP_DEBATE_MAX_MEMBER_COUNT}
    round-speaker-seconds: ${APP_DEBATE_ROUND_SPEAKER_SECONDS}