name: Deploy Web (Frontend)
run-name: Deploy Web to ${{ inputs.environment }} by @${{ github.triggering_actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        type: environment
        required: true

concurrency:
  group: deploy-web
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: self-hosted
    defaults:
      run:
        working-directory: book-talk-ts
    environment:
      name: ${{ inputs.environment }}
    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
      VITE_APP_ENV: production
      VITE_CLOUDFLARE_TURN_URL: ${{ secrets.VITE_CLOUDFLARE_TURN_URL }}
      VITE_CLOUDFLARE_API_TOKEN: ${{ secrets.VITE_CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Validate prerequisites
        run: |
          node --version
          yarn --version

      - name: Install dependencies
        run: yarn install

      - name: Build web package
        run: yarn web build

      - name: Deploy static files
        run: sudo cp -r packages/web/dist/* /var/www/booktalk/frontend/

      - name: Verify deployment
        run: ls -la /var/www/booktalk/frontend/index.html